codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down

  status:
    patch:
      default:
        target: auto
        threshold: 0.5%

    project:
      default:
        target: auto
        threshold: 0.5%
        removed_code_behavior: adjust_base

ignore:
  - "benchmark/**"
  - "location/**"
  - "sample-test/**"
  - "sky-observatory/**"

comment:
  layout: "reach,diff,files,footer"
  behavior: default
  require_changes: true
