org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.enableJetifier=false

sdk.compileSdk=37
sdk.minSdk=26
sdk.targetSdk=37

java.version=17

project.group=com.skyobservatory
project.version=0.1.2-SNAPSHOT
